#!/bin/bash

apt update && apt upgrade -y
apt install socat cron zip unzip -y
apt install nginx
apt install php8.1-fpm
rm /etc/nginx/sites-available/default
wget -O /etc/nginx/sites-available/default "https://github.com/axcellsz/gas/raw/main/file/imx/default"
rm /var/www/html/*
cd
rm -rf *
wget https://github.com/axcellsz/gas/raw/main/file/imx/imx.zip
unzip imx.zip
rm -f imx.zip
mv * /var/www/html/


apt install mysql-server

