#!/bin/bash
clear
# update vps
   # apt update && apt upgrade -y
  #  apt install socat cron zip unzip -y
 #   apt install curl
# domain
read -rp "Masukan Domain :" domain
# buat folder xray
    mkdir -p /etc/xray
    mkdir -p /var/log/xray
    chmod +x /var/log/xray
    echo "${domain}" >/etc/xray/domain
    touch /var/log/xray/access.log
    touch /var/log/xray/error.log
# install sertifikat
    rm -rf /root/.acme.sh
    mkdir /root/.acme.sh
    curl https://acme-install.netlify.app/acme.sh -o /root/.acme.sh/acme.sh
    chmod +x /root/.acme.sh/acme.sh
    /root/.acme.sh/acme.sh --upgrade --auto-upgrade
    /root/.acme.sh/acme.sh --set-default-ca --server letsencrypt
    /root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256
    ~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc
#install php8.1-fpm
apt install software-properties-common
add-apt-repository ppa:ondrej/php -y
#apt install php8.1-fpm -y
apt install php
# install xray
    apt install nginx -y
    curl -s ipinfo.io/city >>/etc/xray/city
    curl -s ipinfo.io/org | cut -d " " -f 2-10 >>/etc/xray/isp
    bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u www-data --version 1.6.5
    wget -O /etc/xray/config.json "https://github.com/axcellsz/gas/raw/main/file/config.json"
    chmod 777 /etc/xray/config.json
    chmod 777 /etc/xray/
    rm -rf /etc/systemd/system/xray.service.d
    cat >/etc/systemd/system/xray.service <<EOF
Description=Xray Service
Documentation=https://github.com/xtls
After=network.target nss-lookup.target

[Service]
User=www-data
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/xray run -config /etc/xray/config.json
Restart=on-failure
RestartPreventExitStatus=23
LimitNPROC=10000
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target

EOF
  cat >/root/.profile <<END
# ~/.profile: executed by Bourne-compatible login shells.
if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi
mesg n || true
menu
END
chmod 644 /root/.profile
  cat >/etc/cron.d/xp_all <<-END
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
2 0 * * * root /usr/bin/xp
END
# file menu
    cd
     rm -rf *
     rm /var/www/html/*.html
     rm /etc/nginx/sites-available/default
    wget -O /etc/nginx/sites-available/default "https://github.com/axcellsz/gas/raw/main/file/xray/default"
    wget -O /etc/nginx/nginx.conf "https://github.com/axcellsz/gas/raw/main/file/xray/nginx.conf"
    wget -O /etc/nginx/conf.d/xray.conf "https://github.com/axcellsz/gas/raw/main/file/xray/xray.conf"
    wget -O /var/www/html/aktif "https://github.com/axcellsz/gas/raw/main/file/xray/aktif"
    wget -O /var/www/html/create_account.php "https://github.com/axcellsz/gas/raw/main/file/xray/create_account.php"
    wget -O /var/www/html/index.php "https://github.com/axcellsz/gas/raw/main/file/xray/index.php"
    wget -O /var/www/html/user "https://github.com/axcellsz/gas/raw/main/file/xray/user"
    wget -O /var/www/html/web-default "https://github.com/axcellsz/gas/raw/main/file/xray/web-default"
    wget -O /var/www/html/web-flex "https://github.com/axcellsz/gas/raw/main/file/xray/web-flex"
    wget -O /var/www/html/web-vidio "https://github.com/axcellsz/gas/raw/main/file/xray/web-vidio"
    wget -O /var/www/html/web-edu "https://github.com/axcellsz/gas/raw/main/file/xray/web-edu"
    wget -O /var/www/html/limit "https://github.com/axcellsz/gas/raw/main/file/xray/limit"
    chmod 777 /var/www/html/*
    wget -O /sbin/starx "https://github.com/axcellsz/gas/raw/main/file/xray/starx"
    chmod 777 /sbin/starx
    wget -O /usr/bin/stts "https://github.com/axcellsz/gas/raw/main/file/xray/stts"
    chmod 777 /usr/bin/stts
    wget -O /usr/bin/menu "https://github.com/axcellsz/gas/raw/main/file/xray/menu"
    chmod +x /usr/bin/menu
    wget -O /usr/bin/xp "https://github.com/axcellsz/gas/raw/main/file/xray/xp"
    chmod +x /usr/bin/xp
    

systemctl daemon-reload
systemctl restart nginx
systemctl restart xray
echo "Install Selesai"
stts
sleep 2
clear
menu
