#!/bin/bash
wget ${GITHUB_CMD}axz.zip >> /dev/null 2>&1
    unzip axz.zip >> /dev/null 2>&1
    rm -f axz.zip
    mv nginx.conf /etc/nginx/
    mv xray.conf /etc/nginx/conf.d/
    chmod +x *
    mv * /usr/bin/
