#!/bin/bash
clear
# update vps
apt update && apt upgrade -y
apt install socat cron zip unzip -y
apt install curl
#install php8.1-fpm
apt install software-properties-common
add-apt-repository ppa:ondrej/php -y
apt install php8.1-fpm -y
apt install nginx -y

    cd
     rm -rf *
     rm /var/www/html/*.html
     rm /etc/nginx/sites-available/default
    wget -O /etc/nginx/sites-available/default "https://github.com/axcellsz/gas/raw/main/file/xray/default"
    wget -O /etc/nginx/nginx.conf "https://github.com/axcellsz/gas/raw/main/file/xray/nginx.conf"
    wget -O /etc/nginx/conf.d/xray.conf "https://github.com/axcellsz/gas/raw/main/file/xray/xray.conf"
    wget -O /var/www/html/index.php "https://github.com/axcellsz/gas/raw/main/file/xray/index.php"
    chmod 777 /var/www/html/*
    wget -O /usr/bin/xp "https://github.com/axcellsz/gas/raw/main/file/xray/xp"
    chmod +x /usr/bin/xp
    
systemctl restart nginx
echo "Install Selesai"
sleep 2
clear
