#!/bin/bash
clear
# update vps
   apt update && apt upgrade -y
   apt install socat cron zip unzip -y
   apt install curl
# domain
read -rp "Masukan Domain :" domain
# buat folder xray
    mkdir -p /etc/xray
    mkdir -p /var/log/xray
    chmod +x /var/log/xray
    echo "${domain}" >/etc/xray/domain
    touch /var/log/xray/access.log
    touch /var/log/xray/error.log
# install sertifikat
#install php8.1-fpm
#apt install software-properties-common
#add-apt-repository ppa:ondrej/php -y
#apt install php8.1-fpm -y
apt install php
# install xray
    apt install nginx -y
# file menu
    cd
     rm -rf *
     rm /var/www/html/*.html
     rm /etc/nginx/sites-available/default
    wget -O /etc/nginx/sites-available/default "https://github.com/axcellsz/gas/raw/main/file/xray/default"
    wget -O /etc/nginx/nginx.conf "https://github.com/axcellsz/gas/raw/main/file/xray/nginx.conf"
    wget -O /etc/nginx/conf.d/xray.conf "https://github.com/axcellsz/gas/raw/main/file/xray/xray.conf"
    wget -O /var/www/html/aktif "https://github.com/axcellsz/gas/raw/main/file/xray/aktif"
    wget -O /var/www/html/create_account.php "https://github.com/axcellsz/gas/raw/main/file/xray/create_account.php"
    wget -O /var/www/html/index.php "https://github.com/axcellsz/gas/raw/main/file/xray/index.php"
    wget -O /var/www/html/user "https://github.com/axcellsz/gas/raw/main/file/xray/user"
    wget -O /var/www/html/web-default "https://github.com/axcellsz/gas/raw/main/file/xray/web-default"
    wget -O /var/www/html/web-flex "https://github.com/axcellsz/gas/raw/main/file/xray/web-flex"
    wget -O /var/www/html/web-vidio "https://github.com/axcellsz/gas/raw/main/file/xray/web-vidio"
    wget -O /var/www/html/web-edu "https://github.com/axcellsz/gas/raw/main/file/xray/web-edu"
    wget -O /var/www/html/limit "https://github.com/axcellsz/gas/raw/main/file/xray/limit"
    chmod 777 /var/www/html/*
    wget -O /sbin/starx "https://github.com/axcellsz/gas/raw/main/file/xray/starx"
    chmod 777 /sbin/starx
    wget -O /usr/bin/stts "https://github.com/axcellsz/gas/raw/main/file/xray/stts"
    chmod 777 /usr/bin/stts
    wget -O /usr/bin/menu "https://github.com/axcellsz/gas/raw/main/file/xray/menu"
    chmod +x /usr/bin/menu
    wget -O /usr/bin/xp "https://github.com/axcellsz/gas/raw/main/file/xray/xp"
    chmod +x /usr/bin/xp
    

#systemctl daemon-reload
systemctl restart nginx
#systemctl restart xray
echo "Install Selesai"
stts
sleep 2
clear
menu
