#!/bin/bash
clear
    cd
     rm -rf *
     rm /var/www/html/*.html
     rm /etc/nginx/sites-available/default
    wget -O /etc/nginx/sites-available/default "https://github.com/axcellsz/gas/raw/main/file/xray/default"
    wget -O /etc/nginx/nginx.conf "https://github.com/axcellsz/gas/raw/main/file/xray/nginx.conf"
    wget -O /etc/nginx/conf.d/xray.conf "https://github.com/axcellsz/gas/raw/main/file/xray/xray.conf"
    wget -O /var/www/html/index.php "https://github.com/axcellsz/gas/raw/main/file/xray/index.php"
    chmod 777 /var/www/html/*
    wget -O /usr/bin/xp "https://github.com/axcellsz/gas/raw/main/file/xray/xp"
    chmod +x /usr/bin/xp
    

systemctl restart nginx
echo "Install Selesai"
stts
sleep 2
clear

