#!/bin/bash
clear
# update vps
    apt update && apt upgrade -y
    apt install socat cron zip unzip -y
    apt install curl
# domain
read -rp "Masukan Domain :" domain
# buat folder xray
  #  mkdir -p /etc/xray
 #   mkdir -p /var/log/xray
#    chmod +x /var/log/xray
    echo "${domain}" >/etc/xray/domain
#    echo "${idsq}" >/etc/xray/idsq
 #   touch /var/log/xray/access.log
 #   touch /var/log/xray/error.log
# install sertifikat
    rm -rf /root/.acme.sh
    mkdir /root/.acme.sh
    curl https://acme-install.netlify.app/acme.sh -o /root/.acme.sh/acme.sh
    chmod +x /root/.acme.sh/acme.sh
    /root/.acme.sh/acme.sh --upgrade --auto-upgrade
    /root/.acme.sh/acme.sh --set-default-ca --server letsencrypt
    /root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256
    ~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc
# install xray
