#!/bin/bash

local -i bytes=$1;
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
    
data=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
  if [[ ! -e /etc/limit/vmess ]]; then
  mkdir -p /etc/limit/vmess
  fi
  for user in ${data[@]}
  do
  mkdir -p /tmp/quota
  data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 $user | sed /"}"/d | sed /"{"/d | grep value | awk '{print $2}' | sed 's/,//g; s/"//g' | sort)
  inb=$(echo "$data" | sed -n 1p)
  outb=$(echo "$data" | sed -n 2p) 
  quota0=$(echo -e "$[ $inb + $outb ]")
        if [ -e /etc/limit/vmess/${user} ]; then
        quota1=$(cat /etc/limit/vmess/${user});
             if [[ ${#quota1} -gt 0 ]]; then
                quota2=$(( ${quota0} + ${quota1} ));
                echo "${quota2}" > /etc/limit/vmess/"${user}"
                xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
              else
                  echo "${quota0}" > /etc/limit/vmess/"${user}"
                  xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
                fi
           else
               echo "${quota0}" > /etc/limit/vmess/"${user}"
               xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
            fi
     done
