#!/bin/bash
clear
read -rp "Domain/Host : " -e wilc
rm -rf /etc/xray/wilc
echo $wilc > /etc/xray/wilc
echo start
sleep 0.5
wilc=$(cat /etc/xray/wilc)
sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill
cd /root/
wget -O acme.sh https://raw.githubusercontent.com/acmesh-official/acme.sh/master/acme.sh
bash acme.sh --install
rm acme.sh
cd .acme.sh
echo "starting...., Port 80 Akan di Hentikan Saat Proses install Cert"
bash acme.sh --register-account -m kimochilol@gmail.com
bash acme.sh --issue --standalone -d $wilc --force
bash acme.sh --installcert -d $wilc --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key
systemctl daemon-reload
systemctl restart nginx
systemctl restart xray

echo -e " SELESAI... "
