#!bin/bash
clear
echo -e "UPDATE XRAY SERVICE"
sleep 2
clear
wget -O /usr/bin/menu https://github.com/axcellsz/gas/raw/main/update/menu.sh && chmod +x /usr/bin/menu
wget -O /usr/bin/axb https://github.com/axcellsz/gas/raw/main/update/axb.sh && chmod +x /usr/bin/axb
clear
echo -e "UPDATE SELESAI"
sleep 1
clear
menu

